version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  migrate:
    image: migrate/migrate
    volumes:
      - ./migrations:/migrations
    depends_on:
      postgres:
        condition: service_healthy
    command:
      - "-path=/migrations"
      - "-database=postgres://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}?sslmode=disable"
      - "up"
    networks:
      - app-network

  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.dev
  #   container_name: itktt_app
  #   ports:
  #     - "${APP_PORT}:${APP_PORT}"
  #   # environment:
  #   #   - DB_HOST=postgres
  #   #   - DB_PORT=5432
  #   #   - DB_USER=${DB_USER}
  #   #   - DB_PASSWORD=${DB_PASSWORD}
  #   #   - DB_NAME=${DB_NAME}
  #   #   - DB_SSLMODE=disable
  #   volumes:
  #     - .:/app
  #     - /app/tmp
  #   depends_on:
  #     - postgres
  #   networks:
  #     - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
